In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

**Part 1 : Question 5**

In [3]:
M = [[-2872.0, 1744.3, -138.7, 77270.0],
    [-273.9, -174.8, -3287.5, 94116.0],
    [-0.7380, -0.6480, -0.1883, 75.633]]
M

[[-2872.0, 1744.3, -138.7, 77270.0],
 [-273.9, -174.8, -3287.5, 94116.0],
 [-0.738, -0.648, -0.1883, 75.633]]

In [4]:
H = [[-2872.0, 1744.3, -138.7],
    [-273.9, -174.8, -3287.5],
    [-0.7380, -0.6480, -0.1883]]
H

[[-2872.0, 1744.3, -138.7],
 [-273.9, -174.8, -3287.5],
 [-0.738, -0.648, -0.1883]]

In [5]:
h = [[77270.0],
    [94116.0],
    [-0.1883]]
h

[[77270.0], [94116.0], [-0.1883]]

In [12]:
R, K  = np.linalg.qr(H)
print("K=", K)
print("R", R)

K= [[ 2885.03132646 -1719.82583214   450.18325349]
 [    0.           339.61309899  3259.46644535]
 [    0.             0.            10.36848054]]
R [[-9.95483125e-01  9.49386423e-02  4.94846659e-05]
 [-9.49383105e-02 -9.95477972e-01 -3.21327546e-03]
 [-2.55803115e-04 -3.20345949e-03  9.99994836e-01]]


In [13]:
K_inverse = np.linalg.inv(K)
K_inverse

array([[ 3.46616687e-04,  1.75529252e-03, -5.66848544e-01],
       [ 0.00000000e+00,  2.94452718e-03, -9.25650340e-01],
       [ 0.00000000e+00,  0.00000000e+00,  9.64461472e-02]])

In [14]:
t = np.matmul(K_inverse, h)
t

array([[ 1.92090920e+02],
       [ 2.77301420e+02],
       [-1.81608095e-02]])